---
name: CI
on:
  push:
jobs:
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Composer dependencies"
        run: "composer install"
      - name: "Run command"
        run: "composer phpstan"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [ code-quality ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Composer dependencies"
        run: "composer ci:install"
      - name: "Run the tests"
        run: "composer tests"
